language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sahil070197/docker-react -f Dockerfile.dev .


script:
  -  docker run -e CI=true sahil070197/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-449192460397"
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY