language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sahil070197/docker-react -f Dockerfile.dev .


script:
  -  docker run -e CI=true sahil070197/docker-react npm run test